apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python-github-test-wreteytey
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-github-test-wreteytey 
  name: python-github-test-wreteytey
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python-github-test-wreteytey 
